<!-- Load Queue widget CSS and jQuery -->
<link href="{$baseUri}css/MultipleFileUpload/jquery.plupload.queue.css" rel="stylesheet" type="text/css" />

<!-- Thirdparty intialization scripts, needed for the Google Gears and BrowserPlus runtimes -->
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/gears_init.js"></script>
<script type="text/javascript" src="http://bp.yahooapis.com/2.4.21/browserplus-min.js"></script>

<!-- Load plupload and all it's runtimes and finally the jQuery UI queue widget -->
{if Environment::isProduction()}
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/min/plupload.full.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/min/jquery.plupload.queue.js"></script>
{else}
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/dev/plupload.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/dev/plupload.gears.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/dev/plupload.html4.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/dev/plupload.html5.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/dev/plupload.silverlight.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/dev/plupload.flash.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/dev/plupload.browserplus.js"></script>

<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/dev/jquery.plupload.queue.js"></script>
{/if}
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/cs.js"></script>

{* GUI Driver *}
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/MultipleFileUpload.js"></script>
