<!--<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/uploadify/swfobject.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/uploadify/jquery.uploadify.v2.1.0.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/uploadify/MultipleFileUpload.js"></script>

<link rel="stylesheet" media="screen,projection,tv" href="{$baseUri}css/MultipleFileUpload/uploadify.css" type="text/css" />-->

<!-- Load Queue widget CSS and jQuery -->
<style type="text/css">@import url({$baseUri}css/MultipleFileUpload/plupload.queue.css);</style>

<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/MultipleFileUpload.js"></script>
<!-- Thirdparty intialization scripts, needed for the Google Gears and BrowserPlus runtimes -->
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/gears_init.js"></script>
<script type="text/javascript" src="http://bp.yahooapis.com/2.4.21/browserplus-min.js"></script>

<!-- Load plupload and all it's runtimes and finally the jQuery UI queue widget -->
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/plupload.full.min.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/jquery.plupload.queue.min.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/cs.js"></script>