<!-- Load Queue widget CSS and jQuery -->
<style type="text/css">@import url({$baseUri}css/MultipleFileUpload/plupload.queue.css);</style>

<!-- Thirdparty intialization scripts, needed for the Google Gears and BrowserPlus runtimes -->
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/gears_init.js"></script>
<script type="text/javascript" src="http://bp.yahooapis.com/2.4.21/browserplus-min.js"></script>

<!-- Load plupload and all it's runtimes and finally the jQuery UI queue widget -->
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/plupload.full.min.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/jquery.plupload.queue.min.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/cs.js"></script>


<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/plupload/MultipleFileUpload.js"></script>
