{*
 * Copyright (c) 2009, Jan Kuchař
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms,
 * with or without modification, are permitted provided
 * that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 *       copyright notice, this list of conditions and the following
 *       disclaimer in the documentation and/or other materials provided
 *       with the distribution.
 *     * Neither the name of the Mujserver.net nor the names of its
 *       contributors may be used to endorse or promote products derived
 *       from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @author     Jan Kuchař
 * @copyright  Copyright (c) 2009 Jan Kuchař (http://mujserver.net)
 * @license    New BSD License
 * @link       http://nettephp.com/cs/extras/multiplefileupload
 *}
 <table cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <div id="{$uploadifyId}" class="uploadify"></div>
        </td>
        <td>
            <span id="{$uploadifyId}ClearQueue" style="display: none;margin-left: 5px;" class="button" onclick="$('#'+{$uploadifyId}).uploadifyClearQueue();">Vymazat frontu</span>
        </td>
        <td id="{$uploadifyId}Count">
            
        </td>
    </tr>
</table>
<div id="{$uploadifyId}-queue" class="ui-widget-content ui-corner-all" style="max-height: 300px;overflow:auto;display: none;margin-top: 5px;margin-bottom: 10px;"></div>

<script type="text/JavaScript">
(function($){

    var queue = $("#{!$uploadifyId}-queue");
    var uploadify = $("#{!$uploadifyId}");
    var box = uploadify.parents("div.withJS");

    // TODO: add this to stylesheet
    $("span.button",box)
	.addClass("ui-state-default ui-corner-all")
	.css("cursor","pointer")
	.css("padding","3px")
	.css("font-size","12px")
	.css("font-family","Constantia,Palatino,'palatino linotype',Georgia,'New York CE',utopia,serif");

    uploadify.uploadify({
	width: 70,
	height: 22,
	wmode: "transparent",
	buttonImg: '{? echo Environment::expand("%baseUri%images/uploadifyButton.png")}',
	uploader: '{? echo Environment::expand("%baseUri%swf/uploadify.allglyphs.swf")}',
	cancelImg: '{? echo Environment::expand("%baseUri%images/cancel.png")}',
	queueID: "{!$uploadifyId}-queue",
	queueSizeLimit: {$maxFiles},
	sizeLimit: {$sizeLimit},
	script: {$backLink},
	scriptData: {
	    token: {$token}
	},
	onInit: function(){
	    box.parent().find(".withoutJS").hide();
	},
	auto: false,
	multi: true,
	onComplete: function(event, ID, fileObj, response, data){
	    jQuery("#" + {$uploadifyId} + ID).hide();
	    return false;
	},
	onSelect: function(event,queueID,fileObj){
		if(fileObj.size > uploadify.uploadifySettings("sizeLimit")) {
			uploadify.trigger({
				type: "sizeLimitExcessed",
				fileObj: fileObj,
				queueID: queueID
			});
			uploadify.uploadifyCancel(queueID);
			return false;
		}
	},
	onSelectOnce: function(){
	    var queue = $("#"+$(this).attr("id")+"-queue");
	    $("#"+$(this).attr("id")+"ClearQueue").fadeIn(500);
	    queue.slideDown(1000,function(){
		$("div.uploadifyQueueItem:first",queue).livequery(function(){
		    $(this).animate({ marginTop:"0px"},200);
		});
	    });
	    $("#"+$(this).attr("id")+"Count").text(uploadify.uploadifySettings("queueSize")+" vybraných souborů");
	    return false;
	},
	simUploadLimit: {$simUploadFiles}
    });
    uploadify.bind("sizeLimitExcessed",function(event){
	alert("soubor '"+event.fileObj.name+"' je moc velký! Bude přeskočen.");
    })
})(jQuery);
</script>