<script type="text/JavaScript" src="{$baseUri}js/MultipleFileUpload/uploadify/swfobject.js"></script>
<script type="text/JavaScript" src="{$baseUri}js/MultipleFileUpload/uploadify/jquery.uploadify.v2.1.0.js"></script>
<script type="text/JavaScript" src="{$baseUri}js/MultipleFileUpload/uploadify/MultipleFileUpload.js"></script>

<link rel="stylesheet" media="screen,projection,tv" href="{$baseUri}css/MultipleFileUpload/uploadify.css" type="text/css" />