<link href="{$baseUri}css/MultipleFileUpload/swfupload.css" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/swfupload/swfupload.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/swfupload/swfupload.queue.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/swfupload/fileprogress.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/swfupload/jquery.swfupload.js"></script>
<script type="text/javascript" src="{$baseUri}js/MultipleFileUpload/swfupload/handlers.js"></script>
<script type="text/javaScript" src="{$baseUri}js/MultipleFileUpload/swfupload/MultipleFileUpload.js"></script>
