@{block #content}

<h1>MultipleFileUpload - form control</h1>
<p>
	Je formulářový prvek, který umožňuje v kompatibilních prohlížečích vybrat soubory při uploadu na server na 1 kliknutí.
</p>




<h2>Dokumentace</h2>
<p>
	Dokumentaci najdete na stránce: <a href="http://nettephp.com/cs/extras/multiplefileupload" target="_BLANK">http://nettephp.com/cs/extras/multiplefileupload</a>.
</p>




<h2>Živý příklad</h2>
{snippet form}
	{ifset $values}
		<h2>Data vrácená formulářem</h2>
		<b>{= count($values["upload"])}</b> přijatých souborů.
		<table>
			<tr>
				<th>
					Název souboru
				</th>
				<th>
					Velikost souboru
				</th>
				<th>
					Mime-type
				</th>
				<th>
					Cesta k souboru
				</th>
			</tr>
			{foreach $values["upload"] AS $file}
			{* $file is instanceof HttpUploadedFile *}
			<tr>
				<th style="text-align: center;">
					{$file->name}
				</th>
				<td style="text-align: center;">
					{$file->size|bytes}
				</td>
				<td>
					{$file->contentType}
				</td>
				<td>
					<i style="font-size: 60%;">{$file->temporaryFile}</i>
				</td>
			</tr>
			{/foreach}
		</table>
		<form class="ajax" action="{link prekresliForm!}" style="padding-top: 10px;">
			<input type="submit" name="tlacitko" value="Zpět na formulář">
		</form>
	{else}
		{widget form}
	{/if}
{/snippet}




<h2>Informace o konfiguraci</h2>
<table cellpadding="5" cellspacing="2" border="2" class="server">
	<tr>
		<th>
			Safe mode
		</th>
		<td>
			{if ini_get("safe_mode")}
				ano
			{else}
				ne
			{/if}
		</td>
	</tr>

	<tr>
		<th>
			open_basedir
		</th>
		<td>
			{if $data = ini_get("open_basedir")}
				{$data}
			{else}
				<i>bez omezení</i>
			{/if}
		</td>
	</tr>

	<tr>
		<th>
			Maximální velikost POST požadavku
		</th>
		<td>
			{= ini_get("post_max_size")}
		</td>
	</tr>

	<tr>
		<th>
			Maximální velikost odesílaných souborů
		</th>
		<td>
			{= ini_get("upload_max_filesize")}
		</td>
	</tr>

	<tr>
		<th>
			{=Framework::NAME} {=Framework::VERSION}{* ({=Framework::PACKAGE}) *}
		</th>
		<td>
			{=Framework::REVISION}
		</td>
	</tr>

	<tr>
		<th>
			Environment name
		</th>
		<td>
			{=Environment::getName()}
		</td>
	</tr>

	<tr>
		<th>
			{=MultipleFileUpload::NAME} version
		</th>
		<td>
			{=MultipleFileUpload::VERSION}
		</td>
	</tr>
</table>
