@{block #content}

<h1>MultipleFileUpload - form control</h1>
<p>
    Je formulářový prvek, který umožňuje v kompatibilních prohlížečích vybrat soubory při uploadu na server na 1 kliknutí.
</p>




<h2>Dokumentace</h2>
<p>
    Dokumentaci najdete na stránce: <a href="http://nettephp.com/cs/extras/multiplefileupload" target="_BLANK">http://nettephp.com/cs/extras/multiplefileupload</a>.
</p>




<h2>Živý příklad</h2>
{snippet form}
  {ifset $values}
      <h2>Data vrácená formulářem</h2>
      {? Debug::dump($values); }
  {else}
      {widget form}
  {/if}
{/snippet}

<form class="ajax" action="{link prekresliForm!}" style="padding-top: 10px;">
    <input type="submit" name="tlacitko" value="prekresliForm!"> - <b>Překresli formulář</b> - pokud je formulář odeslán, vrátí vás to zpět na zadání vstupních dat
</form>



<h2>Nastavení serveru</h2>
<table cellpadding="5" cellspacing="2" border="2" class="server">
    <tr>
        <th>
            Safe mode
        </th>
        <td>
            {? if(ini_get("safe_mode")) echo "ano"; else echo "ne"; }
        </td>
    </tr>
    
    <tr>
        <th>
            open_basedir
        </th>
        <td>
            {? $data = ini_get("open_basedir"); if($data) echo $data; else echo "<i>bez omezení</i>"; }
        </td>
    </tr>
    
    <tr>
        <th>
            Maximální velikost POST požadavku
        </th>
        <td>
            {? echo ini_get("post_max_size")}
        </td>
    </tr>
    
    <tr>
        <th>
            Maximální velikost odesílaných souborů
        </th>
        <td>
            {? echo ini_get("upload_max_filesize")}
        </td>
    </tr>
</table>